// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Roberto Dolfini

using Bilocus.Revit.Pull;
using Xunit;

namespace Bilocus.Revit.Net.Tests
{
    // The text summary of SendSelectionCommand: the only part of the command
    // that can be verified without Revit, together with the pull headers
    // (see SendSelectionMessagesTests).
    public class SendSelectionResultTests
    {
        [Fact]
        public void BuildSummaryText_HappyPath_ReportsCountsAndTimes()
        {
            SendSelectionResult result = new SendSelectionResult
            {
                SentCount = 5,
                TotalTriangles = 240,
                SkippedEmptyCount = 2,
                FailedCount = 0,
                TessellateMs = 12.3,
                SendMs = 4.2
            };

            string text = result.BuildSummaryText();

            Assert.Contains("Sent: 5 elements (240 triangles)", text);
            Assert.Contains("Skipped (no geometry): 2", text);
            Assert.Contains("Skipped (bridge-generated bakes): 0", text);
            Assert.Contains("Failed: 0", text);
            Assert.Contains("Tessellation time: 12 ms", text);
            Assert.Contains("Send time: 4 ms", text);
            Assert.DoesNotContain("WARNING", text);
        }

        // Phase B: DirectShape generated by the bake are skipped to avoid
        // closing the feedback loop, and the summary must say so with its own
        // line. If they ended up among "no geometry", whoever selected them
        // would believe it is a tessellation defect.
        [Fact]
        public void BuildSummaryText_WithBridgeBakes_ReportsThemApartFromEmpty()
        {
            SendSelectionResult result = new SendSelectionResult
            {
                SentCount = 1,
                SkippedEmptyCount = 1,
                SkippedBridgeCount = 3
            };

            string text = result.BuildSummaryText();

            Assert.Contains("Skipped (no geometry): 1", text);
            Assert.Contains("Skipped (bridge-generated bakes): 3", text);
            Assert.Contains("Failed: 0", text);
        }

        [Fact]
        public void BuildSummaryText_WithFailures_NamesLastFailure()
        {
            SendSelectionResult result = new SendSelectionResult
            {
                SentCount = 1,
                FailedCount = 2,
                LastFailureLabel = "Exterior wall [999]",
                LastFailureError = "InvalidOperationException: degenerate geometry"
            };

            string text = result.BuildSummaryText();

            Assert.Contains("Failed: 2", text);
            Assert.Contains("Last failed element: Exterior wall [999] - "
                + "InvalidOperationException: degenerate geometry", text);
        }

        [Fact]
        public void BuildSummaryText_NoFailures_OmitsFailureLine()
        {
            SendSelectionResult result = new SendSelectionResult { SentCount = 1 };

            string text = result.BuildSummaryText();

            Assert.DoesNotContain("Last failed element", text);
        }

        [Fact]
        public void BuildSummaryText_Aborted_AppendsWarningWithReason()
        {
            SendSelectionResult result = new SendSelectionResult
            {
                SentCount = 3,
                Aborted = true,
                AbortReason = "send interrupted after 3 elements, failed on \"Wall [4]\""
            };

            string text = result.BuildSummaryText();

            Assert.Contains(
                "WARNING: send interrupted - send interrupted after 3 elements, failed on \"Wall [4]\"",
                text);
        }

        [Fact]
        public void BuildSummaryText_WithInstances_ReportsSharedMeshes()
        {
            SendSelectionResult result = new SendSelectionResult();
            result.SentCount = 12;
            result.InstanceCount = 10;
            result.SharedMeshCount = 2;

            Assert.Contains("Instanced: 10 elements on 2 shared meshes", result.BuildSummaryText());
        }

        // No instances, no line: the summary of a selection of walls stays
        // exactly as it was.
        [Fact]
        public void BuildSummaryText_WithoutInstances_HasNoInstancedLine()
        {
            SendSelectionResult result = new SendSelectionResult();
            result.SentCount = 3;

            Assert.DoesNotContain("Instanced", result.BuildSummaryText());
        }
    }
}
